# Generated by Django 4.2.5 on 2024-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
    ]
